import { MediaItem } from "../types/media";

export const mediaMock: MediaItem[] = [
  {
    id: "1",
    title: "Non Temere Piccolo Gregge",
    description: "Una predicazione sul superare le paure e confidare in Dio",
    youtubeUrl: "https://www.youtube.com/watch?v=-h8bf6jKJFk",
    thumbnail: "https://img.youtube.com/vi/-h8bf6jKJFk/maxresdefault.jpg",
    publishedAt: "2024-12-15",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "La Fede che Trasforma",
    description: "Predicazione sulla potenza della fede in Cristo",
    youtubeUrl: "https://www.youtube.com/watch?v=yVe8WArZDAY",
    thumbnail: "https://img.youtube.com/vi/yVe8WArZDAY/maxresdefault.jpg",
    publishedAt: "2024-11-28",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Camminare con Gesù",
    description: "Una riflessione sul seguire Cristo ogni giorno",
    youtubeUrl: "https://www.youtube.com/watch?v=ES9XHwnOhcw",
    thumbnail: "https://img.youtube.com/vi/ES9XHwnOhcw/maxresdefault.jpg",
    publishedAt: "2024-11-14",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "La Grazia di Dio",
    description: "Messaggio sulla grazia infinita del Signore",
    youtubeUrl: "https://www.youtube.com/watch?v=_fnpcYt4nSA",
    thumbnail: "https://img.youtube.com/vi/_fnpcYt4nSA/maxresdefault.jpg",
    publishedAt: "2024-10-30",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Vivere nella Speranza",
    description: "Predicazione sulla speranza che abbiamo in Cristo",
    youtubeUrl: "https://www.youtube.com/watch?v=VDAX_4icHlU",
    thumbnail: "https://img.youtube.com/vi/VDAX_4icHlU/maxresdefault.jpg",
    publishedAt: "2024-10-15",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Il Potere della Preghiera",
    description: "Come la preghiera può trasformare la nostra vita",
    youtubeUrl: "https://www.youtube.com/watch?v=h7qUYHPgolY",
    thumbnail: "https://img.youtube.com/vi/h7qUYHPgolY/maxresdefault.jpg",
    publishedAt: "2024-09-28",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "7",
    title: "Amore e Perdono",
    description: "Messaggio sull'amore di Dio e il perdono reciproco",
    youtubeUrl: "https://www.youtube.com/watch?v=GgPbY2n44b8",
    thumbnail: "https://img.youtube.com/vi/GgPbY2n44b8/maxresdefault.jpg",
    publishedAt: "2024-09-10",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "8",
    title: "La Parola di Vita",
    description: "Riflessione sulla potenza della Parola di Dio",
    youtubeUrl: "https://www.youtube.com/watch?v=9WxbbCYpZsE",
    thumbnail: "https://img.youtube.com/vi/9WxbbCYpZsE/maxresdefault.jpg",
    publishedAt: "2024-08-22",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
