import { Playlist } from "../types/media";

export const playlistsMock: Playlist[] = [
  {
    id: "1",
    title: "Genesi",
    description: "Studio approfondito sul libro della Genesi",
    youtubePlaylistUrl:
      "https://www.youtube.com/playlist?list=PLvN86DuEor7yOYwE3XzlhxwcXHkuXsLEK",
    videos: [
      {
        id: "1",
        title: "Genesi 1-3: La Creazione",
        description: "Studio sulla creazione del mondo e la caduta dell'uomo",
        youtubeUrl: "https://www.youtube.com/watch?v=-h8bf6jKJFk",
        thumbnail: "https://img.youtube.com/vi/-h8bf6jKJFk/maxresdefault.jpg",
        publishedAt: "2024-12-15",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "2",
        title: "Genesi 6-9: Il Diluvio",
        description: "Il diluvio universale e l'arca di Noè",
        youtubeUrl: "https://www.youtube.com/watch?v=ES9XHwnOhcw",
        thumbnail: "https://img.youtube.com/vi/ES9XHwnOhcw/maxresdefault.jpg",
        publishedAt: "2024-12-10",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "3",
        title: "Genesi 12-25: Abramo",
        description: "La chiamata di Abramo e la sua fede",
        youtubeUrl: "https://www.youtube.com/watch?v=-h8bf6jKJFk",
        thumbnail: "https://img.youtube.com/vi/-h8bf6jKJFk/maxresdefault.jpg",
        publishedAt: "2024-12-05",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: "2",
    title: "Geremia",
    description: "Studio sul libro del profeta Geremia",
    youtubePlaylistUrl:
      "https://www.youtube.com/playlist?list=PLvN86DuEor7xvrITbv9LkKz7qK_I01ksE",
    videos: [
      {
        id: "3",
        title: "Geremia - Parte 1",
        description: "Introduzione al libro di Geremia",
        youtubeUrl: "https://www.youtube.com/watch?v=g5voBkmULF0",
        thumbnail: "https://img.youtube.com/vi/g5voBkmULF0/maxresdefault.jpg",
        publishedAt: "2024-11-28",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "4",
        title: "Geremia - Parte 2",
        description: "Il messaggio del profeta Geremia",
        youtubeUrl: "https://www.youtube.com/watch?v=VDAX_4icHlU",
        thumbnail: "https://img.youtube.com/vi/VDAX_4icHlU/maxresdefault.jpg",
        publishedAt: "2024-11-25",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "5",
        title: "Geremia - Parte 3",
        description: "Le profezie di Geremia",
        youtubeUrl: "https://www.youtube.com/watch?v=HH94tehhcxQ",
        thumbnail: "https://img.youtube.com/vi/HH94tehhcxQ/maxresdefault.jpg",
        publishedAt: "2024-11-20",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "6",
        title: "Geremia - Parte 4",
        description: "Le lamentazioni di Geremia",
        youtubeUrl: "https://www.youtube.com/watch?v=aqhhnGzJaY4",
        thumbnail: "https://img.youtube.com/vi/aqhhnGzJaY4/maxresdefault.jpg",
        publishedAt: "2024-11-15",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: "3",
    title: "Salmi",
    description: "Studio sui Salmi di Davide",
    youtubePlaylistUrl:
      "https://www.youtube.com/playlist?list=PLvN86DuEor7zzIAltkkwsSGvZqDner-76",
    videos: [
      {
        id: "7",
        title: "Salmi - Parte 1",
        description: "I Salmi di lode e adorazione",
        youtubeUrl: "https://www.youtube.com/watch?v=cpEoYcUpzzY",
        thumbnail: "https://img.youtube.com/vi/cpEoYcUpzzY/maxresdefault.jpg",
        publishedAt: "2024-11-05",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "8",
        title: "Salmi - Parte 2",
        description: "I Salmi di supplica",
        youtubeUrl: "https://www.youtube.com/watch?v=a1ohauGSg5k",
        thumbnail: "https://img.youtube.com/vi/a1ohauGSg5k/maxresdefault.jpg",
        publishedAt: "2024-11-02",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "9",
        title: "Salmi - Parte 3",
        description: "I Salmi di ringraziamento",
        youtubeUrl: "https://www.youtube.com/watch?v=iPSrmrjKE0g",
        thumbnail: "https://img.youtube.com/vi/iPSrmrjKE0g/maxresdefault.jpg",
        publishedAt: "2024-10-28",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "10",
        title: "Salmi - Parte 4",
        description: "I Salmi messianici",
        youtubeUrl: "https://www.youtube.com/watch?v=JOa-vd78ivo",
        thumbnail: "https://img.youtube.com/vi/JOa-vd78ivo/maxresdefault.jpg",
        publishedAt: "2024-10-25",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: "4",
    title: "Le Parabole",
    description: "Studio sulle parabole di Gesù",
    youtubePlaylistUrl:
      "https://www.youtube.com/playlist?list=PLvN86DuEor7wLyVm9Dm6xDG7FFm48EAHT",
    videos: [
      {
        id: "11",
        title: "Le Parabole - Parte 1",
        description: "Introduzione alle parabole di Gesù",
        youtubeUrl: "https://www.youtube.com/watch?v=ucTpzoA6DrY",
        thumbnail: "https://img.youtube.com/vi/ucTpzoA6DrY/maxresdefault.jpg",
        publishedAt: "2024-10-15",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "12",
        title: "Le Parabole - Parte 2",
        description: "Parabole sul Regno di Dio",
        youtubeUrl: "https://www.youtube.com/watch?v=lJdR8dDFMUE",
        thumbnail: "https://img.youtube.com/vi/lJdR8dDFMUE/maxresdefault.jpg",
        publishedAt: "2024-10-12",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "13",
        title: "Le Parabole - Parte 3",
        description: "Parabole sulla misericordia",
        youtubeUrl: "https://www.youtube.com/watch?v=1l4-ky5UEjU",
        thumbnail: "https://img.youtube.com/vi/1l4-ky5UEjU/maxresdefault.jpg",
        publishedAt: "2024-10-08",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "14",
        title: "Le Parabole - Parte 4",
        description: "Parabole sul giudizio",
        youtubeUrl: "https://www.youtube.com/watch?v=D9IFIxadoOw",
        thumbnail: "https://img.youtube.com/vi/D9IFIxadoOw/maxresdefault.jpg",
        publishedAt: "2024-10-05",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: "5",
    title: "Atti degli Apostoli",
    description: "Studio sul libro degli Atti",
    youtubePlaylistUrl:
      "https://www.youtube.com/playlist?list=PLvN86DuEor7yfGae9sE6yxBAMBJqJ4saP",
    videos: [
      {
        id: "15",
        title: "Atti - Parte 1",
        description: "La nascita della Chiesa",
        youtubeUrl: "https://www.youtube.com/watch?v=C9hSt0pI5Ug",
        thumbnail: "https://img.youtube.com/vi/C9hSt0pI5Ug/maxresdefault.jpg",
        publishedAt: "2024-09-28",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "16",
        title: "Atti - Parte 2",
        description: "La diffusione del Vangelo",
        youtubeUrl: "https://www.youtube.com/watch?v=u-LW_BBOpwc",
        thumbnail: "https://img.youtube.com/vi/u-LW_BBOpwc/maxresdefault.jpg",
        publishedAt: "2024-09-25",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "17",
        title: "Atti - Parte 3",
        description: "I viaggi missionari di Paolo",
        youtubeUrl: "https://www.youtube.com/watch?v=Fm9R9IfRW9M",
        thumbnail: "https://img.youtube.com/vi/Fm9R9IfRW9M/maxresdefault.jpg",
        publishedAt: "2024-09-20",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "18",
        title: "Atti - Parte 4",
        description: "La Chiesa primitiva e le persecuzioni",
        youtubeUrl: "https://www.youtube.com/watch?v=GG67a5m-oIE",
        thumbnail: "https://img.youtube.com/vi/GG67a5m-oIE/maxresdefault.jpg",
        publishedAt: "2024-09-15",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: "6",
    title: "Lettera di Giacomo",
    description: "Studio sulla Lettera di Giacomo",
    youtubePlaylistUrl:
      "https://www.youtube.com/@chiesacristianaevangelicae2674/playlists",
    videos: [
      {
        id: "19",
        title: "Lettera di Giacomo - Parte 1",
        description: "La fede che agisce",
        youtubeUrl: "https://www.youtube.com/watch?v=yVe8WArZDAY",
        thumbnail: "https://img.youtube.com/vi/yVe8WArZDAY/maxresdefault.jpg",
        publishedAt: "2024-09-05",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: "7",
    title: "Abramo Amico di Dio",
    description: "Serie sulla vita di Abramo",
    youtubePlaylistUrl:
      "https://www.youtube.com/@chiesacristianaevangelicae2674/playlists",
    videos: [
      {
        id: "20",
        title: "Abramo - La Chiamata",
        description: "La chiamata di Abramo e la sua fede",
        youtubeUrl: "https://www.youtube.com/watch?v=_fnpcYt4nSA",
        thumbnail: "https://img.youtube.com/vi/_fnpcYt4nSA/maxresdefault.jpg",
        publishedAt: "2024-08-25",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: "8",
    title: "Video Generici",
    description: "Predicazioni e testimonianze varie",
    youtubePlaylistUrl:
      "https://www.youtube.com/@chiesacristianaevangelicae2674/videos",
    videos: [
      {
        id: "21",
        title: "Non Temere Piccolo Gregge",
        description: "Predicazione sulla fiducia in Dio",
        youtubeUrl: "https://www.youtube.com/watch?v=h7qUYHPgolY",
        thumbnail: "https://img.youtube.com/vi/h7qUYHPgolY/maxresdefault.jpg",
        publishedAt: "2024-08-15",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "22",
        title: "La Grazia di Dio",
        description: "Messaggio sulla grazia infinita del Signore",
        youtubeUrl: "https://www.youtube.com/watch?v=GgPbY2n44b8",
        thumbnail: "https://img.youtube.com/vi/GgPbY2n44b8/maxresdefault.jpg",
        publishedAt: "2024-08-10",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "23",
        title: "Vivere nella Speranza",
        description: "Predicazione sulla speranza in Cristo",
        youtubeUrl: "https://www.youtube.com/watch?v=9WxbbCYpZsE",
        thumbnail: "https://img.youtube.com/vi/9WxbbCYpZsE/maxresdefault.jpg",
        publishedAt: "2024-08-05",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
];
